import { useState, useEffect, createContext, useContext } from 'react';

export type Language = 'en' | 'ar' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  en: {
    dashboard: 'Dashboard',
    clients: 'Clients',
    invoices: 'Invoices',
    inventory: 'Inventory',
    reports: 'Reports',
    settings: 'Settings',
    billing: 'Billing',
    profile: 'Profile',
    customization: 'System Customization',
    'light-mode': 'Light Mode',
    'dark-mode': 'Dark Mode',
    'total-clients': 'Total Clients',
    'pending-invoices': 'Invoices Pending',
    'inventory-items': 'Inventory Items',
    'total-revenue': 'Total Revenue',
    'sales-overview': 'Sales Overview',
    'recent-activities': 'Recent Activities',
    'upcoming-tasks': 'Upcoming Tasks',
    'run-automation': 'Run Automation',
    'welcome-back': 'Welcome back, here\'s an overview of your business',
    'task-completed': 'Task completed',
    'automation-running': 'Automation running',
    'client-followup-emails': 'Client follow-up emails are being sent',
    'no-widgets-configured': 'No widgets configured. Go to System Customization to add widgets.',
    'log-out': 'Log out',
    'admin': 'Admin',
    'john-doe': 'John Doe',
    'main': 'Main',
    'account': 'Account',
    'language': 'Language',
    'layout': 'Layout',
    'sidebar-navigation': 'Sidebar Navigation',
    'top-navigation': 'Top Navigation',
    'navigation-position': 'Navigation Position',
    'save': 'Save',
    'cancel': 'Cancel',
    'saving': 'Saving...',
    'layout-updated': 'Layout Updated',
    'changes-saved': 'Your changes have been saved successfully',
    'automation-settings': 'Automation Settings',
    'email-settings': 'Email Settings',
    'notification-settings': 'Notification Settings',
    'follow-up-frequency': 'Follow-up Frequency',
    'email-template': 'Email Template',
    'enable-notifications': 'Enable Notifications',
    'daily': 'Daily',
    'weekly': 'Weekly',
    'monthly': 'Monthly',
    'custom-fields': 'Custom Fields',
    'views': 'Views',
    'workflows': 'Workflows',
    'navigation': 'Navigation',
    'dashboard-widgets': 'Dashboard Widgets',
    'add-widget': 'Add Widget',
    'edit-widget': 'Edit Widget',
    'widget-title': 'Widget Title',
    'widget-type': 'Widget Type',
    'widget-size': 'Widget Size',
    'widget-visible': 'Visible',
    'statistic-card': 'Statistic Card',
    'chart': 'Chart',
    'activity-feed': 'Activity Feed',
    'task-list': 'Task List',
    'custom-widget': 'Custom Widget',
    'small': 'Small (1x1)',
    'medium': 'Medium (2x1)',
    'large': 'Large (2x2)',
    'create': 'Create',
    'update': 'Update',
    'delete': 'Delete',
    'configure-automation': 'Configure Automation',
    'entities': 'Entities',
    'add-entity': 'Add Entity',
    'item-hidden': 'Item Hidden',
    'item-hidden-message': 'Navigation item has been hidden. You can restore it in Settings > Customization.',
    'restore': 'Restore',
    'entity-created': 'Entity Created',
    'entity-updated': 'Entity Updated',
    'entity-deleted': 'Entity Deleted',
    'hide-item': 'Hide Item',
    'show-item': 'Show Item',
    'long-press-to-hide': 'Long press to hide',
    'bulk-upload': 'Bulk Upload',
    'upload-users': 'Upload Users',
    'upload-items': 'Upload Items',
    'export-data': 'Export Data',
    'download-template': 'Download Template',
    'csv-file': 'CSV File',
    'upload-successful': 'Upload Successful',
    'upload-failed': 'Upload Failed',
    'export-successful': 'Export Successful',
    'invalid-file-type': 'Invalid File Type',
    'please-upload-csv': 'Please upload a CSV file',
    'required-columns': 'Required columns',
    'optional': 'optional',
    'required': 'required',
  },
  ar: {
    dashboard: 'لوحة التحكم',
    clients: 'العملاء',
    invoices: 'الفواتير',
    inventory: 'المخزون',
    reports: 'التقارير',
    settings: 'الإعدادات',
    billing: 'الفوترة',
    profile: 'الملف الشخصي',
    customization: 'تخصيص النظام',
    'light-mode': 'الوضع الفاتح',
    'dark-mode': 'الوضع الداكن',
    'total-clients': 'إجمالي العملاء',
    'pending-invoices': 'الفواتير المعلقة',
    'inventory-items': 'عناصر المخزون',
    'total-revenue': 'إجمالي الإيرادات',
    'sales-overview': 'نظرة عامة على المبيعات',
    'recent-activities': 'الأنشطة الحديثة',
    'upcoming-tasks': 'المهام القادمة',
    'run-automation': 'تشغيل الأتمتة',
    'welcome-back': 'مرحباً بعودتك، إليك نظرة عامة على عملك',
    'task-completed': 'تم إنجاز المهمة',
    'automation-running': 'تشغيل الأتمتة',
    'client-followup-emails': 'يتم إرسال رسائل متابعة العملاء',
    'no-widgets-configured': 'لم يتم تكوين أي ودجات. اذهب إلى تخصيص النظام لإضافة ودجات.',
    'log-out': 'تسجيل الخروج',
    'admin': 'مدير',
    'john-doe': 'جون دو',
    'main': 'الرئيسي',
    'account': 'الحساب',
    'language': 'اللغة',
    'layout': 'التخطيط',
    'sidebar-navigation': 'شريط التنقل الجانبي',
    'top-navigation': 'شريط التنقل العلوي',
    'navigation-position': 'موضع التنقل',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'saving': 'جاري الحفظ...',
    'layout-updated': 'تم تحديث التخطيط',
    'changes-saved': 'تم حفظ التغييرات بنجاح',
    'automation-settings': 'إعدادات الأتمتة',
    'email-settings': 'إعدادات البريد الإلكتروني',
    'notification-settings': 'إعدادات الإشعارات',
    'follow-up-frequency': 'تكرار المتابعة',
    'email-template': 'قالب البريد الإلكتروني',
    'enable-notifications': 'تفعيل الإشعارات',
    'daily': 'يومي',
    'weekly': 'أسبوعي',
    'monthly': 'شهري',
    'custom-fields': 'حقول مخصصة',
    'views': 'العروض',
    'workflows': 'سير العمل',
    'navigation': 'التنقل',
    'dashboard-widgets': 'ودجات لوحة التحكم',
    'add-widget': 'إضافة ودجة',
    'edit-widget': 'تعديل الودجة',
    'widget-title': 'عنوان الودجة',
    'widget-type': 'نوع الودجة',
    'widget-size': 'حجم الودجة',
    'widget-visible': 'مرئي',
    'statistic-card': 'بطاقة إحصائية',
    'chart': 'رسم بياني',
    'activity-feed': 'تغذية النشاط',
    'task-list': 'قائمة المهام',
    'custom-widget': 'ودجة مخصصة',
    'small': 'صغير (1×1)',
    'medium': 'متوسط (2×1)',
    'large': 'كبير (2×2)',
    'create': 'إنشاء',
    'update': 'تحديث',
    'delete': 'حذف',
    'configure-automation': 'تكوين الأتمتة',
    'entities': 'الكيانات',
    'add-entity': 'إضافة كيان',
    'item-hidden': 'تم إخفاء العنصر',
    'item-hidden-message': 'تم إخفاء عنصر التنقل. يمكنك استعادته في الإعدادات > التخصيص.',
    'restore': 'استعادة',
    'entity-created': 'تم إنشاء الكيان',
    'entity-updated': 'تم تحديث الكيان',
    'entity-deleted': 'تم حذف الكيان',
    'hide-item': 'إخفاء العنصر',
    'show-item': 'إظهار العنصر',
    'long-press-to-hide': 'اضغط مطولاً للإخفاء',
    'bulk-upload': 'تحميل مجمع',
    'upload-users': 'تحميل المستخدمين',
    'upload-items': 'تحميل العناصر',
    'export-data': 'تصدير البيانات',
    'download-template': 'تحميل القالب',
    'csv-file': 'ملف CSV',
    'upload-successful': 'تم التحميل بنجاح',
    'upload-failed': 'فشل التحميل',
    'export-successful': 'تم التصدير بنجاح',
    'invalid-file-type': 'نوع ملف غير صالح',
    'please-upload-csv': 'يرجى تحميل ملف CSV',
    'required-columns': 'الأعمدة المطلوبة',
    'optional': 'اختياري',
    'required': 'مطلوب',
  },
  es: {
    dashboard: 'Panel de Control',
    clients: 'Clientes',
    invoices: 'Facturas',
    inventory: 'Inventario',
    reports: 'Reportes',
    settings: 'Configuración',
    billing: 'Facturación',
    profile: 'Perfil',
    customization: 'Personalización del Sistema',
    'light-mode': 'Modo Claro',
    'dark-mode': 'Modo Oscuro',
    'total-clients': 'Total de Clientes',
    'pending-invoices': 'Facturas Pendientes',
    'inventory-items': 'Elementos de Inventario',
    'total-revenue': 'Ingresos Totales',
    'sales-overview': 'Resumen de Ventas',
    'recent-activities': 'Actividades Recientes',
    'upcoming-tasks': 'Tareas Próximas',
    'run-automation': 'Ejecutar Automatización',
    'welcome-back': 'Bienvenido de vuelta, aquí tienes un resumen de tu negocio',
    'task-completed': 'Tarea completada',
    'automation-running': 'Automatización en ejecución',
    'client-followup-emails': 'Se están enviando correos de seguimiento a clientes',
    'no-widgets-configured': 'No hay widgets configurados. Ve a Personalización del Sistema para agregar widgets.',
    'log-out': 'Cerrar sesión',
    'admin': 'Administrador',
    'john-doe': 'John Doe',
    'main': 'Principal',
    'account': 'Cuenta',
    'language': 'Idioma',
    'layout': 'Diseño',
    'sidebar-navigation': 'Navegación Lateral',
    'top-navigation': 'Navegación Superior',
    'navigation-position': 'Posición de Navegación',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'saving': 'Guardando...',
    'layout-updated': 'Diseño Actualizado',
    'changes-saved': 'Tus cambios han sido guardados exitosamente',
    'automation-settings': 'Configuración de Automatización',
    'email-settings': 'Configuración de Email',
    'notification-settings': 'Configuración de Notificaciones',
    'follow-up-frequency': 'Frecuencia de Seguimiento',
    'email-template': 'Plantilla de Email',
    'enable-notifications': 'Habilitar Notificaciones',
    'daily': 'Diario',
    'weekly': 'Semanal',
    'monthly': 'Mensual',
    'custom-fields': 'Campos Personalizados',
    'views': 'Vistas',
    'workflows': 'Flujos de Trabajo',
    'navigation': 'Navegación',
    'dashboard-widgets': 'Widgets del Panel',
    'add-widget': 'Agregar Widget',
    'edit-widget': 'Editar Widget',
    'widget-title': 'Título del Widget',
    'widget-type': 'Tipo de Widget',
    'widget-size': 'Tamaño del Widget',
    'widget-visible': 'Visible',
    'statistic-card': 'Tarjeta de Estadística',
    'chart': 'Gráfico',
    'activity-feed': 'Feed de Actividad',
    'task-list': 'Lista de Tareas',
    'custom-widget': 'Widget Personalizado',
    'small': 'Pequeño (1x1)',
    'medium': 'Mediano (2x1)',
    'large': 'Grande (2x2)',
    'create': 'Crear',
    'update': 'Actualizar',
    'delete': 'Eliminar',
    'configure-automation': 'Configurar Automatización',
    'entities': 'Entidades',
    'add-entity': 'Agregar Entidad',
    'item-hidden': 'Elemento Oculto',
    'item-hidden-message': 'El elemento de navegación ha sido ocultado. Puedes restaurarlo en Configuración > Personalización.',
    'restore': 'Restaurar',
    'entity-created': 'Entidad Creada',
    'entity-updated': 'Entidad Actualizada',
    'entity-deleted': 'Entidad Eliminada',
    'hide-item': 'Ocultar Elemento',
    'show-item': 'Mostrar Elemento',
    'long-press-to-hide': 'Mantén presionado para ocultar',
    'bulk-upload': 'Carga Masiva',
    'upload-users': 'Cargar Usuarios',
    'upload-items': 'Cargar Elementos',
    'export-data': 'Exportar Datos',
    'download-template': 'Descargar Plantilla',
    'csv-file': 'Archivo CSV',
    'upload-successful': 'Carga Exitosa',
    'upload-failed': 'Carga Fallida',
    'export-successful': 'Exportación Exitosa',
    'invalid-file-type': 'Tipo de Archivo Inválido',
    'please-upload-csv': 'Por favor sube un archivo CSV',
    'required-columns': 'Columnas requeridas',
    'optional': 'opcional',
    'required': 'requerido',
  }
};

export const LanguageContext = createContext<LanguageContextType | null>(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const useLanguageProvider = () => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('app-language') as Language;
    if (savedLanguage && ['en', 'ar', 'es'].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
    
    // Update document direction and language
    document.documentElement.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  const isRTL = language === 'ar';

  return {
    language,
    setLanguage,
    t,
    isRTL
  };
};
